spring:
  config:
    activate:
      on-profile: prod

  datasource:
    master:
      jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 50
      minimum-idle: 30
      idle-timeout: 30000

    replica:
      jdbc-url: jdbc:postgresql://${DB_REPLICA_HOST}:${DB_REPLICA_PORT}/${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 50
      minimum-idle: 30
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  data:
    redis:
      host: ${REDIS_HOST}        # ElastiCache Primary Endpoint
      port: ${REDIS_PORT:6379}   # 기본 6379
      # 클러스터 모드 사용 시 Lettuce 클러스터 옵션
      lettuce:
        cluster:
          enabled: ${REDIS_CLUSTER_ENABLED:false}
          nodes: ${REDIS_CLUSTER_NODES:}


server:
  port: ${APP_PORT:8080}

logging:
  level:
    com.part2.monew: INFO
    com.part2.monew.handlerinterceptor.LogInterceptor: WARN

monew:
  batch:
    news-collection:
      enabled: ${BATCH_NEWS_COLLECTION_ENABLED:true}
      backup:
        enabled: ${BATCH_BACKUP_ENABLED:true}
      s3-upload:
        enabled: ${BATCH_S3_UPLOAD_ENABLED:true}
